version: '3.7'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.4
    ports:
      - 2379:2379
    environment:
      # https://etcd.io/docs/v3.5/op-guide/configuration/#command-line-flags
      ETCD_NAME: test
      ETCD_SNAPSHOT_COUNT: 100
      ETCD_HEARTBEAT_INTERVAL: 1000
      ETCD_ELECTION_TIMEOUT: 10000
      ETCD_MAX_SNAPSHOTS: 4
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379

